app:
  camel:
    source-directory: work
    target-directory: data
    json-schema: schema.json
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/mem:mydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: